### ISSUE TITLE
Typo in error message in lib/dom.js

### ISSUE THREAD

**Issue by rrthomas** [xmldom/xmldom#228] opened 2021-04-24 21:16 UTC
`unknow Class` should be `unknown Class`.

Thanks for xmldom!

**Comment by karfau** [comment] 2021-04-25 06:10
Thank you for noticing.

I have a question, since this is an "internal method": Did you have a situation, in which that error was triggered? And if so, can you share with us how to reproduce it?

**Comment by rrthomas** [comment] 2021-04-25 11:42
Good question! No, I was just reading the source to track down another problem, which I'll be filing a PR for shortly.

**Comment by brodybits** [comment] 2021-05-09 18:03
What is the status of this?

**Comment by rrthomas** [comment] 2021-05-09 18:15
@brodybits just to be clear, as far as I'm concerned, the typo I reported here is just a single character missing in an error message (no help required). As I said, I didn't get the error unexpectedly, I just noticed the message in the source code while looking for something else. The PR I said I would file for an unrelated problem has already been merged (#229).

**Comment by karfau** [comment] 2021-05-09 18:36
From my perspective I would not start to invest any time into it right now, since I consider many other issues more important.

Most likely the next time I need to deal with some related code/ error messages, I would fix it along the way.

**Comment by karfau** [comment] 2021-08-23 18:14
@rrthomas I'm currently trying to reduce the amount of open issues to the ones we are planning to handle with regards to some priorities.

I think if this is an issue for somebody, I would encourage them to just file a PR with a fix (it can easily be done from without leaving GitHub).

That's why I decided to close this one.

**Closed by karfau** 2021-08-23 18:14 UTC
Labels: enhancement, good first issue, help wanted

**Comment by rrthomas** [comment] 2021-08-23 18:28
I have filed #294.
