### ISSUE TITLE
The current types include globals that don't exist in Node

### ISSUE THREAD

**Issue by karfau** [xmldom/xmldom#285] opened 2021-08-20 04:34 UTC
This is a "copy" of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49953 
since we copied the type definitions from DefinitlyTyped to fix the (types) regression introduced in #278.

The current types reference TypeScript's DOM typings with `/// <reference lib="dom" />`. This causes any module that imports xmldom to get the entire DOM typings, including globals like `document`.

With those globals defined we lose errors when accidentally referencing them, which can obviously cause crashes.

It'd be great if we would only provide the types that we use and export, like `DOMImplementation`, `Document`, `Node`, etc.

Related "main thread": #191

**Comment by amacneil** [comment] 2021-08-24 04:41
Despite this reference in `index.d.ts`, when upgrading from `xmldom:0.6.0` to `@xmldom/xmldom:0.7.2` typescript complained about missing dom libraries and I had to explicitly add `"lib": ["dom"]` to `tsconfig.json`. 

I'm not sure how to explain this, but it seems that this line might be ignored for types included in a package (versus loading from DefinitelyTyped)?

**Comment by karfau** [comment] 2021-08-24 10:17
@amacneil thank you for providing those details.
But I'm surprised by that, since I would have expected that even with version 0.6.0 and the types package, it would have been required to add `lib: ["dom"]` if you typescript target is not a browser.
The `reference` comment is still in place in the current type definition, so that didn't change, but from my understanding this doesn't tell ts to make the types available globally, it just acts like an import.
And I would be surprised if the types package would contain anything that has an impact on the typescript build config of downstream projects. But I guess we could check the content of the package to find it out.

Sadly I'm currently not aware how to improve/resolve this issue without completely changing how we define those types.

**Comment by amacneil** [comment] 2021-08-24 16:57
I agree, it is surprising behavior. I created a repro here: https://github.com/amacneil/xmldom-types-repro

You can see the build output here: https://github.com/amacneil/xmldom-types-repro/actions/runs/1163442338

I found that for both the old and new version, if the package imports `xmldom` (or `@xmldom/xmldom`), the `reference` is applied and `"lib": ["dom"]` is not needed.

However, if `@types/xmldom` simply exists in the package.json (but is not imported in any files), typescript still honors the `reference`. This is not the case with bundled types in `@xmldom/xmldom`. That explains why we had to add `"lib": ["dom"]` to on our package (the `hooks` package did not use xmldom, but the types existed elsewhere in our monorepo so would have applied everywhere, which is bad!).

I don't know why this behavior happens, but at least this proves what is happening.

**Comment by defunctzombie** [comment] 2021-08-24 17:13
One thing worth calling out is that typescript default behavior is to load all the type definitions in the @types folder. It considers the @types folder a typeRoot (https://www.typescriptlang.org/tsconfig). This might contribute to different behavior for triple slash reference directives.

**Comment by karfau** [comment] 2022-02-20 20:55
Since we have not heard anybody having issue with this for quite a while, I will close this issue now.

If this is still an issue for you, please leave a comment here and I will reopen it.

**Comment by tjhorner** [comment] 2024-02-27 21:53
Having issues with this. When importing `@xmldom/xmldom` anywhere in a project, the triple-slash reference to the `dom` lib makes DOM types available _everywhere_ in my project, even when they aren't supposed to be. Our project has multiple different platform targets (service worker, DOM, etc.) so it's important for us to have compile-time safeguards against using APIs that may not exist at runtime.

Here is the relevant TypeScript issue: https://github.com/microsoft/TypeScript/issues/33111

A common solution other library maintainers have landed on is to just vendor the necessary DOM types into their projects, for example: https://github.com/sindresorhus/is/pull/93

An ugly workaround is to import the JS file directly, bypassing the type declarations:

```
import { DOMParser } from "@xmldom/xmldom/lib/index"
```

But then you won't get the typings.

**Comment by karfau** [comment] 2024-02-28 05:20
@tjhorner thx for reporting this.
Can you please help us to create a reproduction for this?
The reason for closing the issue was missing reports/reproduction.
As soon as we have a reproduction I would love to add it to the checks of this repository.

**Comment by defunctzombie** [comment] 2024-02-28 14:03
@karfau Was the above reproduction repo posted by @amacneil not sufficient to reproduce?

<img width="935" alt="image" src="https://github.com/xmldom/xmldom/assets/84792/994dc12c-cb1f-417b-b257-e1b7b67d7f97">

**Comment by danon** [comment] 2024-03-16 09:52
I encountered this issue myself. Obviously the types in `@xmldom` shouldn't reference TypeScript DOM, since they're not compatible.

**Comment by karfau** [comment] 2024-09-04 20:20
@danon @tjhorner @amacneil @defunctzombie thx for all the patience, I'm happy to announce that I finished the work on #717 which should resolve this issue.

I will see if I can reproduce using the offered reproduciton, but if you want to have a look and e.g. copy the index.d.ts file from that branch into your node_modules temporarily, to give feedback before it is released as 0.9.1, this is your chance :muscle:

**Closed** 2024-09-05 03:44 UTC
Labels: bug, help-wanted, invalid, types

**Comment by danon** [comment] 2024-09-05 08:15
> If I understand correctly, `2-new-import` should fail like this when, right?

Yes, I believe so. Good work! Thank you!
