### ISSUE TITLE
A parameter initializer is only allowed in a function or constructor implementation. [plugin angular-compiler]

### ISSUE THREAD

**Issue by Jobvdb** [xmldom/xmldom#718] opened 2024-09-04 07:22 UTC
**Describe the bug**
When upgrading from 0.8.10 to 0.9.0, upon building my angular app, it returns 
✘ [ERROR] TS2371: A parameter initializer is only allowed in a function or constructor implementation. [plugin angular-compiler]

    node_modules/@xmldom/xmldom/index.d.ts:287:3:
      287 │       mimeType: MIME_TYPE = MIME_TYPE.XML_TEXT
          ╵       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**To Reproduce**
ng build

**Expected behavior**
That it builds

**Runtime & Version:**
xmldom version: 0.9.0
runtime version:  -
other related software and version: -
 "typescript": "^5.5.4", 
Angular 18.2.2

**Additional context**

**Comment by karfau** [comment] 2024-09-05 06:27
I'm pretty certain this is a duplicate of #713 so it should have been fixed as part of the latest release 0.9.1

If it is not, please provide some more steps to reproduce the issue and I will reopen it.

**Closed by karfau** 2024-09-05 06:27 UTC
Labels: bug, duplicate, needs investigation
