### ISSUE TITLE
Works in Rhino/Graal?

### ISSUE THREAD

**Issue by ShawnTalbert** [xmldom/xmldom#152] opened 2020-10-20 15:28 UTC
I'm trying to get this working in a Rhino environment (or Graal would work too)

I notice the `lib/` files assume an environment where `exports` is defined. As far as I know that's not the case for Rhino or Graal by default?

The readme mentions this work sin Rhino so I must be missing something?

p.s. sorry to file an issue for this as it's perhaps not a _bug_ but I didn't see any other forum.

**Comment by karfau** [comment] 2020-10-21 06:24
Sorry, I have no experience with those enironments.
But from #83 I know that @joestringer seems to be using it, so maybe he can help?

Maybe you can also provide some more details about your setup, like versions, ...?
Any links or instruction into how to reproduce this might also help.

**Comment by ShawnTalbert** [comment] 2020-10-21 15:25
As a workaround I put AMD wrappers around the code (which provides an `exports`). The Rhino environment I'm in uses AMD as the module system.

Since AMD tries to play nice with CommonJS I think the workaround is successful, but did mean I had to modify the source, which is sad.

Perhaps a good solution would be to have some standard 'auto detection' of the module system in use like many other libraries do to make them work in both the Browser/NodeJS/elsewhere automatically?

For example, TypeScript emits something like the following boilerplate code for _UMD_ modules that seem to play nicely in both CommonJS and AMD environments.

```typescript
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "...other dependencies here..."], factory);
    }
})(function (require, exports) {
  // main code here
});
```

https://github.com/umdjs/umd

**Comment by joestringer** [comment] 2020-10-22 06:32
If it helps, I used xmldom here with Rhino 1.7.12: https://github.com/oganexon/BTE-tools/commit/09b63f3943fe3a24a1932d7fbe315143ff039ebe

This relies on commit 8f02868cae42ee2b8329130ffe989c000162ea66 of xmldom, otherwise xmldom would fail at runtime as described in the commit message.

**Comment by ShawnTalbert** [comment] 2020-10-31 05:20
Thanks @joestringer but I don't see how that addresses the module system issue. Maybe your Rhino 1.7.12 environment wasn't using a module system? The Rhino environment I run code in also has an AMD module constraint.

**Comment by karfau** [comment] 2021-01-21 04:18
@ShawnTalbert I'm closing this issue as wontfix, feel free to reopen and/or add more information.

**Closed by karfau** 2021-01-21 04:18 UTC
