### ISSUE TITLE
Maintainance take over timeline from v0.1.27 to 0.3.0

### ISSUE THREAD

**Issue by karfau** [xmldom/xmldom#62] opened 2020-06-27 07:17 UTC
The purpose of this issue is to list how the package has been modified since the last version published by the original author.
The information is mostly derived from commits, github issues and is meant to be an easily readable timeline. As such it focuses only on the details of actual code changes, other changes are only mentioned.

### 28th Nov 2016
- `v0.1.27` was **published** on npm by @jindw as [xmldom](https://www.npmjs.com/package/xmldom/v/0.1.27) and [xmldom-alpha](https://www.npmjs.com/package/xmldom-alpha/v/0.1.27) with the same content (except the package name). The [commit](0ee90e6092ffeeaada9d81d000a30d7f127413b4) was pushed by @jinjinyun on the same day. (Was tagged in xmldom/xmldom with that version by @brodybits on the 19th Dec 2019.)

### 29th Nov 2016
- `license` field in `package.json` was fixed in f62560dbc9ced5bfe119f2f2c4bae29917133c4a by @jindw by merging https://github.com/jindw/xmldom/pull/178

### 6th Jan 2017
- [Conditional converting of HTML entities](https://github.com/jindw/xmldom/pull/80) was merged into master in 6b47d09be5aca3e0b4687812dfccf452482bc660 by @jindw
- BREAKING introduced regression regarding `&nbsp;` in some (x)html documents see #57 

### 11th Jan 2017
56eb39f82dd2052a683b1870fb1f4a105e184f66 by @jinjinyun contains several changes
- `dom-parser.js` changed html mime type check to `/\/x?html?$/`, consistently in `dom-parser.js`
- `dom.js` fixed serialization issue for missing document element ([example that failed on `toString()` before this change](https://github.com/xmldom/xmldom/blob/a58dcf7a265522e80ce520fe3be0cddb1b976f6f/test/parse/unclosedcomment.js#L10-L11))
- extracted `entities.js`
- widened regression #57 to all documents treated as html

### 8th May 2017
ffd8cac8f65a56286bc654946aaaa49620018d49 by @jinjinyun 
- `dom-parser.js` requires `entities.js` initially upfront and no longer when invoking `parseFromString`

### 9th May 2017 
- @jindw published ffd8cac8f65a56286bc654946aaaa49620018d49 to npm as [`xmldom-alpha@0.1.28`](https://www.npmjs.com/package/xmldom-alpha/v/0.1.28) (that still has [depentents](https://www.npmjs.com/package/xmldom-alpha/v/0.1.28?activeTab=dependents))
- @jinjinyun pushed 0be2ae910a8a22c9ec2cac042e04de4c04317d2a that updates the package.json to match the previously published version and [removes the `Object.create` check from the `_extends` method of `dom.js` that added a `__proto__` property](https://github.com/xmldom/xmldom/commit/0be2ae910a8a22c9ec2cac042e04de4c04317d2a#diff-7d1c5d97786fdf9af5446a241d0b6d56L19-L22) (BREAKING?).
- @jinjinyun pushed 366159a76a181ce9a0d83f5dc48205686cfaf9cc that removed code that added a `__proto__` property that seems to "only" be used by a ["test"](https://github.com/jindw/xmldom/blob/366159a76a181ce9a0d83f5dc48205686cfaf9cc/test/3rd-cases/o3xml.js#L6)

### 19th Dec 2019
- all changes by @brodybits 
- pushed tags for prev versions as stated above
#### on the [`v0.1.x` branch](https://github.com/xmldom/xmldom/tree/0.1.x)
- was branched from f62560dbc9ced5bfe119f2f2c4bae29917133c4a created on 29th Nov 2016, so it only contained the license fix
- published and tagged `v0.1.29`, `v0.1.30`, `v0.1.31` with only `package.json` metadata fixes.

#### on the `master` branch 
- following the changes of 366159a76a181ce9a0d83f5dc48205686cfaf9cc from 9th of May 2017
- corrections in `package.json`

### 20th Dec 2019
- all changes by @brodybits 
#### on the `master` branch 
- formatting/corrections in `package.json`
- various changes in `.travis.yml`
- published 1bcd95e788aa233bed2fac70da9508cc407434c5 as version/tag 0.2.0 (without `v` prefix!), (first published version of `xmldom` containing the regression listed above)
- corrections in `package.json`
- published 1bcd95e788aa233bed2fac70da9508cc407434c5 as version/tag 0.2.1

### 2nd March 2020
- @kethinov [announced the fork in the original repo](https://github.com/jindw/xmldom/issues/259)

### CHANGELOG

Starting from version [0.3.0](https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md#030) the changes are documented in https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md

**Comment by karfau** [comment] 2020-06-27 12:38
@brodybits I hope this is what you were thinking about when you asked for such an issue in #59 . 
We could either link this issue in the CHANGELOG.md or even integrate it's content there.

Maybe we should even pin this issue, so it's easier to find and for people to ask related questions.

Feel free to edit the description as you like.

**Comment by brodybits** [comment] 2020-06-28 21:26
Thanks for the research and updates!

My original idea in PR #59 was to track regressions and other suddenly changed behavior somewhere for discussion.

I would definitely favor moving most of this information into CHANGELOG.md, maybe part of PR #63, and just track the (possible) regressions and other suddenly changed behavior in an issue for discussion.

Here is my understanding of the possible and definite regressions found so far:

- nbsp issue raised in #57
- from test update in 37d5fb9dc2dad9670a59ec76d9a64d483d3ec199: "The `assert.throw` fails since the code no longer throws exceptions when parsing fails."
- changes related to `__proto__` property

Some quick comments on the description:

- xmldom vs xmldom-alpha did cause me some confusion in the past, already raise discussion in #7
- I think the v0.1.28-not-published tag should be renamed to something like v0.1.28-xmldom-alpha or v0.1.28-xmldom-alpha-only
- the versions I published from the 0.1.x branch should be listed in CHANGELOG.md in PR #63, I think
- I think the regression in #57 was also published in v0.1.29, v0.1.30, v0.1.31

**Comment by brodybits** [comment] 2020-06-29 01:37
I pushed `v0.1.28-xmldom-alpha` tag to make it clear that v0.1.28 was only released in xmldom-alpha. Maybe we should delete `v0.1.28-not-published` tag now?

**Comment by karfau** [comment] 2020-06-29 03:59
> I pushed `v0.1.28-xmldom-alpha` tag to make it clear that v0.1.28 was only released in xmldom-alpha. Maybe we should delete `v0.1.28-not-published` tag now?

I have to tell you the both `v0.1.28-...` tags are acctualy on the wrong commit.
I compared the content of the package on npm with the code of the repo and the tags are one commit off, as described in the description they should be on ffd8cac.

I think it makes sense to also tag the other versions that have been published to xmldom-alpha with such a tag. So all the information is in one place.

And I agree that we should drop the `v0.1.28-not-published` tag, I don't think it currently helps anybody.

**Comment by karfau** [comment] 2020-06-29 04:04
> I think the regression in #57 was also part of the releases that I published in v0.1.29, v0.1.30, v0.1.31

No, since you branched it of from the license fix commit f62560db (:relieved: :+1: ), they are not part of it.

**Comment by karfau** [comment] 2020-06-29 04:47
Question: Are you creating these changelog entries by hand? I know there are tools for that, some also work if there are silly commit messages (like in our repo in the past).
If you have any preference let me know, otherwise I will test some to add entries in #63

**Comment by brodybits** [comment] 2020-06-30 02:46
Thanks, I may need a few days to look at this. And the existing CHANGELOG.md was made by someone else in PR #28, which I think you know is after the fact. So I would not consider the changelog to be really automated.

**Comment by karfau** [comment] 2020-09-17 20:15
@brodybits in my comments above there are still some questions unanswered. For me to integrate this information into the changelog we need to resolve those.
I would prefer you reread my comments and if there is anything not clear we continue the discussion.
But if that doesn't work for you, I can also invest the time to list all open questions in a new comment.

**Comment by karfau** [comment] 2020-09-27 20:15
I took the liberty to clean up the tags in the way we talked about:
I deleted the tags `v0.1.28-xmldom-alpha` and `v0.1.28-not-published` that were pointing to a wrong commit and created `xmldom-alpha@v0.1.28` (to stick to a well known naming scheme and the `v` prefeix that was present in all versions back then) on the correct commit.

**Closed** 2020-10-02 20:07 UTC
